### ISSUE TITLE
[Bug Report] Couldn't pass ProxyPingEvent to minimotd-velocity

### ISSUE THREAD

**Issue by foxonecup** [jpenilla/MiniMOTD#100]
[12:12:11 ERROR]: Couldn't pass ProxyPingEvent to minimotd-velocity
java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at xyz.jpenilla.minimotd.lib.platform_velocity.xyz.jpenilla.minimotd.common.MiniMOTD.parse(MiniMOTD.java:113) ~[?:?]
        at xyz.jpenilla.minimotd.lib.platform_velocity.xyz.jpenilla.minimotd.common.MiniMOTD.createMOTD(MiniMOTD.java:95) ~[?:?]
        at xyz.jpenilla.minimotd.velocity.PingListener.handle(PingListener.java:56) ~[?:?]
        at xyz.jpenilla.minimotd.velocity.PingListener.lambda$onProxyPingEvent$0(PingListener.java:49) ~[?:?]
        at com.velocitypowered.api.event.EventTask$1.execute(EventTask.java:66) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.execute(VelocityEventManager.java:546) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:605) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by jpenilla** [comment]
You need the latest velocity 3.1.2 snapshot
