### ISSUE TITLE
[Bug Report] Crash related to the Create mod

### ISSUE THREAD

**Issue by serega404** [jpenilla/MiniMOTD#116]
**Describe the bug**
The server breaks down if you put the [Deployer](https://create.fandom.com/wiki/Deployer) from the Create mod on the ground

**To Reproduce**
1. Install [Create 0.5.0c](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
2. Install MiniMOTD
3. Place"[Deployer](https://create.fandom.com/wiki/Deployer)"
4. See server crash

**Expected behavior**
The server will not crash.

**Server Software and Version:**
 - Vendor: Fabric
 - Minecraft Version: 1.18.2
 - Output of /version command: not exist
 - Server jar name: fabric-server-mc.1.18.2-loader.0.14.9-launcher.0.11.0.jar

**Logs**

> java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at net.minecraft.class_3244.handler$zeo000$adventure$initTracking(class_3244.java:2698)
	at net.minecraft.class_3244.<init>(class_3244.java:203)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:20)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:18)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer.<init>(DeployerFakePlayer.java:57)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initHandler(DeployerTileEntity.java:142)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initialize(DeployerTileEntity.java:135)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:67)
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.tick(KineticTileEntity.java:93)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:168)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jpenilla** [comment]
duplicate #104

**Comment by itsdinkd** [comment]
you should just write a warning "Not compatible with Create, Industrial Revolution, and others because I won't release a version without the fake player feature that conflicts with other mods"

**Comment by jpenilla** [comment]
As explained before (https://github.com/jpenilla/MiniMOTD/issues/104#issuecomment-1149363461), this has nothing to do with the fake player count feature whatsoever. As also explained before, the issue is on the side of create (https://github.com/jpenilla/MiniMOTD/issues/104#issuecomment-1174034442). Other mods like carpet and computercraft used to have similar issues, but have long since fixed them. The honus to display a warning really isn't on me, if anyone, here.
