### ISSUE TITLE
1.18.2 error

### ISSUE THREAD

**Issue by Nthing734** [jpenilla/MiniMOTD#122]
when i run it on the 1.18.2,it give me this

[18:01:28 ERROR]: Error occurred while enabling MiniMOTD v2.0.9 (Is it up to date?)
java.lang.IllegalStateException: Failed to load MiniMOTD. Ensure your config files are without errors.
        at xyz.jpenilla.minimotd.common.MiniMOTD.<init>(MiniMOTD.java:56) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.bukkit.MiniMOTDPlugin.onEnable(MiniMOTDPlugin.java:52) ~[minimotd-universal-2.0.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:667) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1166) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to load config
        at xyz.jpenilla.minimotd.common.config.ConfigManager.loadConfigs(ConfigManager.java:78) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.common.MiniMOTD.<init>(MiniMOTD.java:54) ~[minimotd-universal-2.0.9.jar:?]
        ... 12 more
Caused by: xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.serialize.CoercionFailedException: [player-count-settings, max-players-enabled] of type java.lang.Boolean: Failed to coerce input value of type class java.lang.String to boolean
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.serialize.BooleanSerializer.deserialize(BooleanSerializer.java:63) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.serialize.BooleanSerializer.deserialize(BooleanSerializer.java:36) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.lib.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.common.config.ConfigLoader.load(ConfigLoader.java:105) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.common.config.ConfigManager.loadConfigs(ConfigManager.java:72) ~[minimotd-universal-2.0.9.jar:?]
        at xyz.jpenilla.minimotd.common.MiniMOTD.<init>(MiniMOTD.java:54) ~[minimotd-universal-2.0.9.jar:?]
        ... 12 more

**Comment by jpenilla** [comment]
Invalid config at `player-count-settings.max-players-enabled`
