### ISSUE TITLE
[Bug Report] 1.19.2 fabric server crashes when using miniMOTD with Create

### ISSUE THREAD

**Issue by QyInvoLing** [jpenilla/MiniMOTD#127]
**Describe the bug**
The server immediately crashes after the console prints "Done!"(a vanilla notice when the server is ready)

**Crash-report.txt**
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-01-12 23:53:53
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at net.minecraft.class_3244.handler$zfl000$adventure$initTracking(class_3244.java:3044)
	at net.minecraft.class_3244.<init>(class_3244.java:242)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:20)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer.<init>(DeployerFakePlayer.java:58)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initHandler(DeployerTileEntity.java:146)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initialize(DeployerTileEntity.java:139)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:67)
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.tick(KineticTileEntity.java:94)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:172)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3244.handler$zfl000$adventure$initTracking(class_3244.java:3044)
	at net.minecraft.class_3244.<init>(class_3244.java:242)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:20)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer.<init>(DeployerFakePlayer.java:58)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initHandler(DeployerTileEntity.java:146)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initialize(DeployerTileEntity.java:139)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:67)
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.tick(KineticTileEntity.java:94)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:172)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: create:deployer // com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity
	Block: Block{create:deployer}[axis_along_first=false,facing=east]
	Block location: World: (10,66,21), Section: (at 10,2,5 in 0,4,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{create:deployer}[axis_along_first=false,facing=east]
	Block location: World: (10,66,21), Section: (at 10,2,5 in 0,4,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-42,68,10), Section: (at 6,4,10 in -3,4,0; chunk contains blocks -48,-64,0 to -33,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 3898143 game time, 39705 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 8970 (now: false), thunder time: 20167 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 18.0.2.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1563231232 bytes (1490 MiB) / 3225419776 bytes (3076 MiB) up to 8434745344 bytes (8044 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 4800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.89
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1636
	Graphics card #1 versionInfo: DriverVersion=27.20.11032.6002
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34221.66
	Virtual memory used (MB): 25139.98
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 55.21
	JVM Flags: 0 total; 
	Fabric Mods: 
		amplifiednether: Amplified nether 1.2
		animated_guns: Simple Animated Guns 1.0
		architectury: Architectury 6.4.62
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continents: Continents 1.1
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			forgeconfigapiport: Forge Config API Port 4.2.6
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		essential_commands: Essential Commands 0.30.0-mc1.19.2
			ec-core: Essential Commands Core 1.3.0-mc1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 1.33
			playerabilitylib: Pal 1.6.0
		fabric-api: Fabric API 0.72.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.11
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		immersive_aircraft: Immersive Aircraft 0.2.0+1.19.2
		java: Java HotSpot(TM) 64-Bit Server VM 18
		mca: Minecraft Comes Alive 7.4.0+1.19.2
		minecraft: Minecraft 1.19.2
		minimotd-fabric: MiniMOTD 2.0.9
			adventure-platform-fabric: adventure-platform-fabric 5.4.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.1
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pfm: Paladin's Furniture 1.1.1
		phosphor: Phosphor 0.8.1
		prefab: Prefab 4.2.4
		structory: Structory 1.0.1
		styledchat: Styled Chat 2.0.2+1.19.2
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			player-data-api: Player Data API 0.2.2+1.19.2
			predicate-api: Predicate API 0.1.0+1.19.2
		terrablender: TerraBlender 2.0.1.136
		terralith: Terralith 2.3
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.10
		twilightforest: The Twilight Forest 4.2.333
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.642+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.642+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.642+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.642+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.642+1.19.2
				porting_lib_models: Porting Lib Models 2.1.642+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.642+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.642+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.642+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.642+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.642+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.642+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.642+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.642+1.19.2
						porting_lib_common: Porting Lib Common 2.1.642+1.19.2
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, Fabric Mods, file/PFM Recipes Addition - 1.19.X - 23.1.8.zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by jpenilla** [comment]
Duplicate #116, also only the latest version of MiniMOTD is supported, which on Fabric is currently for 1.19.3.
