### ISSUE TITLE
[Feature Request] Request MiniMOTD compatibility with version 1.20

### ISSUE THREAD

**Issue by Chun-QiuCC** [jpenilla/MiniMOTD#138]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when  
```
The existing version of MiniMOTD is only compatible with 1.20.1
```

**Describe the solution you'd like**
```
Request MiniMOTD compatibility with version 1.20, existing version only compatible with version 1.20.1  
```

**Describe alternatives you've considered**
```
Attempting to directly use version 2.0.13, but unable to run
```

**Additional context**
~~~
[21:50:36] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MiniMOTD' (minimotd-fabric) 2.0.13 with any version that is compatible with:
		 - minecraft 1.20
Unmet dependency listing:
	 - Mod 'MiniMOTD' (minimotd-fabric) 2.0.13 requires version 1.20.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
~~~

**Comment by jpenilla** [comment]
1.20 is a bugged version that was superseded by protocol-compatible 1.20.1 within days. 1.20.1 is a trivial update for modders. No plans to release a build with 1.20 support.
