### ISSUE TITLE
[Bug Report] Crashing on 23w45a

### ISSUE THREAD

**Issue by Ectalite** [jpenilla/MiniMOTD#145]
**Describe the bug**
When starting my fabric server on 23w45a, it crashes with message:
`[22:18:50] [main/INFO]: Vanilla bootstrap took 8208 milliseconds
[22:18:51] [main/INFO]: Done initializing MiniMOTD
[22:18:51] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adventure-platform-fabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.23w45a-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.Hash$Strategy net.minecraft.class_156.method_655()'
	at net.kyori.adventure.platform.fabric.impl.ServerArgumentTypes.<clinit>(ServerArgumentTypes.java:53) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
	at net.kyori.adventure.platform.fabric.impl.AdventureCommon.setupCustomArgumentTypes(AdventureCommon.java:234) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
	at net.kyori.adventure.platform.fabric.impl.AdventureCommon.onInitialize(AdventureCommon.java:182) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	... 7 more`

**To Reproduce**
1. Install latest fabric version (0.14.24) on latest snapshot (23w45a)
2. Use version fabric-mc1.20.2-2.0.14 of MiniMOTD
3. Server crashes

**Server Software and Version:**
 - Vendor: Fabric 0.14.24 (Fabric API 0.90.8+1.20.3)
 - Minecraft Version: 23w45a

**Additional context**
I understand if you won't fix it because of the server being on snapshot.

**Comment by jpenilla** [comment]
2.0.14 is for 1.20.2, I don't have to support snapshots
