### ISSUE TITLE
[Bug Report] java.lang.Error: Method became inaccessible: ProxyPingEvent

### ISSUE THREAD

**Issue by mibby** [jpenilla/MiniMOTD#62]
Waterfall dev 419
MiniMOTD dev 4b61e912

Downgrading to MiniMOTD dev 454439a1 resolves the issue -- no errors. So assuming it is caused by commit https://github.com/jpenilla/MiniMOTD/commit/27fbefdd9c0f88c4c68c49c9b21b15dd5d3552d8

```
java.lang.Error: Method became inaccessible: ProxyPingEvent(connection=[/censored:60615] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, protocol=754), players=ServerPing.Players(max=1000, online=0, sample=null), description=§f§bcensored, modinfo=ServerPing.ModInfo(type=FML, modList=[])))
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:269) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:245) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:278) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:30) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:515) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalAccessException: class net.md_5.bungee.event.EventHandlerMethod cannot access a member of class xyz.jpenilla.minimotd.bungee.PingListener with modifiers "public"
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:558) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	... 39 more
[23:25:06] [Netty Worker IO Thread #1/ERROR]: [/censored:60616] <-> InitialHandler - encountered exception
java.lang.Error: Method became inaccessible: ProxyPingEvent(connection=[/censored:60616] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, protocol=754), players=ServerPing.Players(max=1000, online=0, sample=null), description=§f§bcensored, modinfo=ServerPing.ModInfo(type=FML, modList=[])))
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:217) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.protocol.packet.LegacyPing.handle(LegacyPing.java:33) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalAccessException: class net.md_5.bungee.event.EventHandlerMethod cannot access a member of class xyz.jpenilla.minimotd.bungee.PingListener with modifiers "public"
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:558) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	... 36 more
[23:25:09] [Netty Worker IO Thread #2/ERROR]: [/censored:34220] <-> InitialHandler - encountered exception
java.lang.Error: Method became inaccessible: ProxyPingEvent(connection=[/censored:34220] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, protocol=47), players=ServerPing.Players(max=1000, online=0, sample=null), description=§f§bcensored, modinfo=ServerPing.ModInfo(type=FML, modList=[])))
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:269) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:245) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:278) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:30) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:515) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalAccessException: class net.md_5.bungee.event.EventHandlerMethod cannot access a member of class xyz.jpenilla.minimotd.bungee.PingListener with modifiers "public"
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:558) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:b9bcf83:419]
	... 39 more
```

**Comment by jpenilla** [comment]
It looks like bungee's reflective event handler invocation doesn't like my package private class. Thanks for submitting such a detailed report. I'll push a commit which should fix this shortly.
